[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
alembic = "==1.5.2"
#appdirs = "==1.4.3"
#attrs = "==19.3.0"
black = "==19.10b0"
#click = "==7.0"
GeoAlchemy2 = "*"
#Mako = "==1.1.0"
#MarkupSafe = "==1.1.1"
more-itertools = "*"
#pathspec = "==0.7.0"
psycopg2 = "*"
#python-dateutil = "==2.8.0"
#python-editor = "==1.0.4"
#regex = "==2020.1.8"
SQLAlchemy = "==1.4.15"
#toml = "==0.10.0"
#typed-ast = "==1.4.1"
sqlalchemy-citext = "*"

[dev-packages]
alembic-verify = "==0.1.4"   # loosen?
#atomicwrites = "==1.3.0"
#importlib-metadata = "==0.23"
pytest = "*"
pytest-describe = "*"
pytest-mock = "*"
#py = "==1.8.0"
#scramp = "==1.1.0"
#"testing.common.database" = "==2.0.3"
"testing.postgresql" = "*"  # source of problem?
#pg8000 = "==1.13.2"
#pluggy = "==0.13.0"
#six = "==1.12.0"
#sqlalchemy-diff = "==0.1.5"
#SQLAlchemy-Utils = "==0.37.3"
zipp = "==3.5.0"  # necessary? See https://github.com/pacificclimate/pycds/pull/104


# We can't use python_version because with a Ubuntu 18.04 base image
# (which we must use in order to access old versions of Postgres etc.),
# the Python test-matrix installations fail.
# [requires]
python_version = "3.10"
